#ifndef CURRENTSCHEMA_H_
#define CURRENTSCHEMA_H_

#include "src/db/schema/Schema.h"

class Interface;

/**
 * The current schema (the implementation is autogenerated)
 */
class CurrentSchema: public Schema
{
	public:
		CurrentSchema (Interface &interface);
		virtual ~CurrentSchema ();

		virtual void up (OperationMonitorInterface monitor=OperationMonitorInterface::null);
		virtual void down (OperationMonitorInterface monitor=OperationMonitorInterface::null);

		virtual QList<quint64> getVersions ();
};

#endif
