#ifndef _CurrentSchema_h
#define _CurrentSchema_h

#include "src/db/schema/Schema.h"

class Database;

/**
 * The current schema (the implementation is autogenerated)
 */
class CurrentSchema: public Schema
{
	public:
		CurrentSchema (Database &database);
		virtual ~CurrentSchema ();

		virtual void up ();
		virtual void down ();

		virtual QList<quint64> getVersions ();
};

#endif
