#ifndef CURRENTSCHEMA_H_
#define CURRENTSCHEMA_H_

#include "src/db/schema/Schema.h"

namespace Db { namespace Interface { class Interface; } }

/**
 * The current schema (the implementation is autogenerated)
 */
class CurrentSchema: public Schema
{
	public:
		CurrentSchema (Db::Interface::Interface &interface);
		virtual ~CurrentSchema ();

		virtual void up ();
		virtual void down ();

		virtual QList<quint64> getVersions ();
};

#endif
