#!/bin/bash

host=$1
timeout=$2
pidfile=$3
lockfile="/tmp/$$.lockfile"

ping_host ()
{
	ping -c 1 $host >/dev/null
	rm -f $lockfile
}

cleanup ()
{
	if [ -e "$lockfile" ]; then rm $lockfile; fi
	exit
}

trap cleanup TERM INTERRUPT HUP

while true; do
	touch $lockfile
	ping_host $host &
	pingpid=$!
	sleep $timeout
	if [ -e "$lockfile" ]; then
		kill $pingpid
		cat $pidfile |xargs -n 1 kill
		rm $lockfile
	fi
done

