#!/bin/bash

#echo $((`head -n 1 build`+1)) >build
#echo Build: `head -n 1 build`
#echo "Build `head -n 1 build`, `date -Iminute`, `hostname`">>build.log
#echo "#define VERSION \"Version `head -n 1 major`.`head -n 1 minor` (build `head -n 1 build`) (`date -I`)\"">version.h

# Ohne build
#echo "Build `date -Iminute`, `hostname`">>build.log
if [ -e .svn ]; then
	if [ -n "`which svnversion`" ]; then
		svnstring=`svnversion ..`
	else
		svnstring="svn"
	fi

	echo "#define VERSION \"Version `head -n 1 major`.`head -n 1 minor`-${svnstring} (`date -I`)\"">version.h
else
	echo "#define VERSION \"Version `head -n 1 major`.`head -n 1 minor` (`date -I`)\"">version.h
fi

