#!/bin/bash

versionstring=`head -n 1 version`

if [ -e .svn ]; then
	if [ -n "`which svnversion`" ]; then
		svnstring=`svnversion ..`
	else
		svnstring="svn"
	fi

	echo "#define VERSION \"Version ${versionstring}-${svnstring} (`date -I`)\"">version.h
else
	echo "#define VERSION \"Version ${versionstring} (`date -I`)\"">version.h
fi

