#!/bin/bash

while true; do
	#for i in `seq 1 2`; do
	#	seq -s ' ' 1 $i
	#	sleep 1
	#done
	#seq -s ' ' 1 3

	echo "long"
	sleep 1
	echo "long, very, very long"
	sleep 1
	echo "even longer, longer, longer, longer"
	sleep 1
	echo "so long that it will easily fit in one line with shifting, without wrapping"
	sleep 2
	echo "extremely long. in fact, this text is do long that we will have to wrap it or else the text won't fit in the column."
	sleep 2

	#echo "_____"
	#sleep 1
	#echo "WWWWW"
done

