#!/bin/bash

fifo=/tmp/wind

if [ ! -e $fifo ]; then mkfifo $fifo; fi

dir=0
dir_increment=1
vel=10
vel_increment=2

write_wind ()
{
	while true; do
		dir=$(($dir+$dir_increment))
		if [ $dir -ge 360 ]; then dir=$(($dir-360)); fi

		vel=$(($vel+$vel_increment))
		if [ $vel -ge 17 ]; then vel_increment=-3; fi
		if [ $vel -le 5 ]; then vel_increment=2; fi

		echo "$dir°/$vel kt"
		sleep 3
	done
}

trap "" SIGPIPE

while true; do
	echo "Restarting wind generator"
	write_wind >$fifo
done

