.TH "STARTKLADDE" "1" "2012-06-15" "" ""

.SH NAME
startkladde \- flight logging for flying clubs
.SH SYNOPSIS

\fBstartkladde\fR [ \fB--q\fR ] [ \fB--colored-labels\fR ] [ \fB--no-full-screen\fR ] [ \fB--enable-shutdown\fR ]

.SH "DESCRIPTION"
.PP
\fBstartkladde\fR is a program for logging flights at
airfields or glider sites for flying clubs.
.SH "OPTIONS"
.PP
These programs follow the usual GNU command line syntax,
with long options starting with two dashes (`-').  A summary of
options is included below.
.TP
\fB-q \fR
Print queries to standard output as they are executed.
.TP
\fB--colored-labels \fR
Show labels with an opaque background (for layout testing).
.TP
\fB--no-full-screen \fR
Don't show the main window in full screen on startup.
.TP
\fB--enable-shutdown \fR
Enables the shutdown menu entry which exits the program with exit code 69.
.SH "SEE ALSO"
.PP
http://startkladde.sourceforge.net

