#!/bin/bash

date=$1

if [ -z "$date" ]; then
	echo "Usage: $0 date"
	echo "date must be in ISO format (yyyy-mm-dd)."
	exit 1
fi

year=`echo $date |cut -d - -f 1`
month=`echo $date |cut -d - -f 2`
day=`echo $date |cut -d - -f 3`

if [ -z "$year" ]; then echo "Year error"; fi
if [ -z "$month" ]; then echo "Month error"; fi
if [ -z "$day" ]; then echo "Day error"; fi

if [ "$month" -eq 01 ]; then monthname="Jan"; fi
if [ "$month" -eq 02 ]; then monthname="Feb"; fi
if [ "$month" -eq 03 ]; then monthname="Mar"; fi
if [ "$month" -eq 04 ]; then monthname="Apr"; fi
if [ "$month" -eq 05 ]; then monthname="May"; fi
if [ "$month" -eq 06 ]; then monthname="Jun"; fi
if [ "$month" -eq 07 ]; then monthname="Jul"; fi
if [ "$month" -eq 08 ]; then monthname="Aug"; fi
if [ "$month" -eq 09 ]; then monthname="Sep"; fi
if [ "$month" -eq 10 ]; then monthname="Oct"; fi
if [ "$month" -eq 11 ]; then monthname="Nov"; fi
if [ "$month" -eq 12 ]; then monthname="Dec"; fi

shortday=`echo $day |sed "s/^0//"`
shortmonth=`echo $month |sed "s/^0//"`
datestring="$monthname $shortday, $year"

wget --quiet -O - "http://www.timeanddate.com/worldclock/astronomy.html?n=964&obj=sun&month=$month&year=$year&day=$day"	\
	|grep -i "$datestring"

#	|grep "^<tr class=\"c" 

