#!/bin/bash

# Get the time left until sunset.
# Usage:
#   $0 [datafile]

# The file from where to get the sunset times
# Format:
# yyyy-mm-dd<tab>hh:mm
# date           sunset (UTC)
datafile=$1
if [ -z "$1" ]; then
	datafile=sunsets
fi

# Check if the file exists
if [ ! -e "$datafile" ]; then
	echo "Datendatei \"$datafile\" nicht gefunden"
	exit 1
fi

# Check if the file is readble
if [ ! -r "$datafile" ]; then
	echo "Datendatei \"$datafile\" nicht lesbar"
	exit 1
fi

# Find the sunset
sunset=$(grep $(date -I) $datafile |cut -s -f 2 |head -n 1)

# Check if the sunset was found
if [ -z "$sunset" ]; then
	echo "Datum `date -I` nicht in Datendatei vorhanden"
	exit 1
fi

# Determine time components
ss_hour=`echo $sunset |cut -s -d ':' -f 1`
ss_minute=`echo $sunset |cut -s -d ':' -f 2`
now_hour=`date -u +%H`
now_minute=`date -u +%M`

# Check if the file is in correct format
if [ -z "$ss_hour" ]; then
	echo "Datendatei nicht im korrekten Format"
	exit 1
fi

# Check if the file is in correct format
if [ -z "$ss_minute" ]; then
	echo "Datendatei nicht im korrekten Format"
	exit 1
fi

# Remove leading zeros (or else the value will be interpreted as octal)
ss_hour=`echo $ss_hour |sed "s/^0//"`
ss_minute=`echo $ss_minute |sed "s/^0//"`
now_hour=`echo $now_hour |sed "s/^0//"`
now_minute=`echo $now_minute |sed "s/^0//"`


# Calculate the time until sunset
time_left=$(((60*$ss_hour+$ss_minute)-(60*$now_hour+$now_minute)))

# Determine the components of the time left
hours_left=$(($time_left/60))
minutes_left=$(($time_left%60))

# Remove the leading minus from the minutes and add a leading 0 if it has only
# one digit
minutes_left=$(echo $minutes_left |sed "s/^-//" |sed "s/^\(.\)$/0\1/")

# If time_left is between -60 and 0, there will be no negative sign on the hour
# component. So it is also removed and added later.
hours_left=$(echo $hours_left |sed "s/^-//")

# Make the output string
string_left="$hours_left:$minutes_left"

# Output with the correct color
if [ $time_left -lt 0 ]; then
	echo "<font color=\"#FF0000\">-$string_left</font>"
else
	echo "<font color=\"#000000\">$string_left</font>"
fi

