#!/bin/bash

# Plasma (from KDE) has sunset time calculation code

datafile=$1
if [ -z "$1" ]; then
	datafile=sunsets
fi

#date=`date -I`
date=`date +%m-%d`
sunset=`grep "^$date" $datafile |head -n 1 |cut -f 2`

if [ -z "$sunset" ]; then
	echo "Datum $date nicht in Datendatei vorhanden"
else
	echo "${sunset}Z"
fi

