#!/bin/bash

# Metar funktioniert. Fuer TAF und STAF muss man noch etwas nacharbeiten.

debug()
{
        echo "$@" >/dev/stderr
}


loc="$1"

if [ -z "$loc" ]; then
        echo "Kein Flugplatz angegeben"
        exit 1
fi

echo "Rufe METAR für $loc ab..."

url="http://weather.noaa.gov/cgi-bin/mgetmetar.pl?cccc=$loc"
#url="http://weather.noaa.gov/cgi-bin/mgettaf.pl?cccc=$loc"
# mgetmetar, mgettaf, mgetstaf


#debug "Get METAR for $loc"

file=/tmp/metar.$$

while ! wget --timeout=5 -O $file "$url" 2>/dev/null; do
	:
done

cat $file \
        |grep -A 20 '<font face="courier" size = "5">' \
        |grep -B 20 '</font>' \
        |grep -v '<' \
        |grep -v '>' \
        |grep '.'

rm $file

